services:
  - type: web
    name: groqcrawl
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
