services:
  - type: web
    name: playwright-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
